### ISSUE TITLE
DSA in Python

### ISSUE THREAD

**Issue by tasha06** [tasha06/Python-Programs#3]

**Comment by NidhiNivedita6** [comment]
Could you please assign me this @tasha06 ?

**Comment by tasha06** [comment]
> Could you please assign me this @tasha06 ?

You can submit your pr @NidhiNivedita6

**Comment by khushboorathore10** [comment]
Hi , I Want to submit Simple graph  algorithms . Please assign me this issue @tasha06

**Comment by tasha06** [comment]
Go ahead @khushboorathore10

**Comment by piyushP7pravin** [comment]
Please assign this to me

**Comment by tasha06** [comment]
You may submit your PR @piyushP7pravin

**Comment by Mayankjha997** [comment]
hey @tasha06 ;
can i add merge sort in java

**Comment by tasha06** [comment]
Sure. Go ahead! @Mayankjha997
