### ISSUE TITLE
Mini Projects

### ISSUE THREAD

**Issue by tasha06** [tasha06/Python-Programs#4]

**Comment by Kiinitix** [comment]
I would like to add a tic-tac-toe game.

**Comment by tasha06** [comment]
You can submit your Pull request @Kiinitix

**Comment by nishitjain1204** [comment]
I would like to add a quiz game

**Comment by AcousticCh** [comment]
if you assign me i could add a linux network scanner or another similar command line automation tool

**Comment by tasha06** [comment]
@nishitjain1204 and @AcousticCh You can submit your PR

**Comment by Mayankjha997** [comment]
Hello @tasha06 ;
can I add merge-sort in python, please assign this to me

**Comment by Mayankjha997** [comment]
hello @tasha06 
I want to add merge-sort in python, please assign this issue to me

**Comment by tasha06** [comment]
Go ahead @Mayankjha997

**Comment by khushboorathore10** [comment]
Hi , I want to work on this topic via adding a chatbot using python . Please assign this issue to me @tasha06

**Comment by passionlord** [comment]
i would love to write program in python

**Comment by tasha06** [comment]
You may submit your pull request @khushboorathore10  and @passionlord

**Comment by passionlord** [comment]
hi @tasha06  after merging pull request i checked in hacktoberfest page its showing this project is not participating 😥

**Comment by waridrox** [comment]
@passionlord yeah that is bound to happen if people are just spamming for the sake of getting a t shirt 🤣🤣

**Comment by passionlord** [comment]
@waridrox yeah 😂

**Comment by tasha06** [comment]
> ![participating](https://user-images.githubusercontent.com/62416874/135809548-b666b542-3a49-49f5-9bdb-4a227384395e.PNG)
> 
> hi @tasha06 after merging pull request i checked in hacktoberfest page its showing this project is not participating 😥

Please check again. I have already added the required label while merging.

**Comment by piyushP7pravin** [comment]
i want to add chatting application

**Comment by tasha06** [comment]
Go ahead @piyushP7pravin

**Comment by piyushP7pravin** [comment]
> Go ahead @piyushP7pravin

Project not participating

**Comment by YashMali597** [comment]
I would like to add to add a Motion Detector. Can you assign me this?

**Comment by YashMali597** [comment]
I would like to add a Python Motion Detector .

**Comment by tasha06** [comment]
Go ahead @YashMali597

**Comment by waridrox** [comment]
Guys move beyond T SHIRTS!!!!! Seriously, you can add many useless projects here, but that won't benefit you in the real world. Just wear that t shirt in pride and show off that's the best you can do 👀 Shame on you ppl.

**Comment by waridrox** [comment]
especially ppl like @tasha06 who join GitHub just for the sole purpose of hacktoberfest noice.

**Comment by tasha06** [comment]
@waridrox  The reason why I created this issue is so that beginners can also contribute and learn things.
Without knowing the purpose of anything we should not assume or write bad about someone or something. 
Even if one chooses to contribute in order to get the t-shirt, it's there choice. And no one has forced you to contribute in it.
Thank you for taking out time to search this issue and comment on it :)

**Comment by waridrox** [comment]
Sure sure why not beginners should get a chance who's stopping that...but instead of straightaway asking them to upload their projects, you could've asked them for small code changes / feature additions in a project...

**Comment by tasha06** [comment]
Instead of suggesting me, you can take these steps to help them. I did what I thought is good. I didn't ask anyone to submit any big project. It's just small beginner friendly code which all of us write in the beginning of our coding journey. And fyi, this issue has actually helped a few beginners who are new to coding and/or open source. Plus everyone is contributing according to their will.
Also, I request you kindly stop spamming here.

**Comment by waridrox** [comment]
Ya sure, how ironic is it that the one who joined GitHub this month just for the sake of getting t shirts, is calling me the spam.

**Comment by tasha06** [comment]
How ironic when one should focus on their career or on themselves, they are busy watching other people's life
It would be better if you mind your own business rather than poking your nose in mine :)
